package at.htlkaindorf.dorjab18.simulation;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;

/**
 *
 * @author dorjab18
 */
public class DefaultSimulation extends AbstractSimulation {
    private double time = 0;
    
    public DefaultSimulation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void timeElapsed(double deltaTime) {
        this.time += deltaTime;
    }

    @Override
    public void reset() {
        this.time = 0;
    }

    @Override
    public void draw(Graphics2D g2d) {
        g2d.setColor(Math.abs(time)%1000 < 500?Color.RED:Color.GREEN);
        g2d.setFont(new Font(Font.DIALOG, Font.BOLD, 30));
        g2d.drawString("It works!", 100, 50);
        
        g2d.setColor(Color.BLACK);
        g2d.setFont(new Font(Font.DIALOG, Font.BOLD, 20));
        g2d.drawString("Time passed: " + time + " ms", 100, 100);
    }

    @Override
    public String getSimulationName() {
        return "Default Simulation";
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
