package example.rotatorExample;

import at.htlkaindorf.dorjab18.simulation.AbstractSimulation;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;

/**
 * @author dorjab18 (Code in draw: HS)
 */
public class RotatorExampleSimulation extends AbstractSimulation {
    private double time;
    
    private Rotator rot;
    
    /**
     * Creates new form RotationExampleSimulation
     */
    public RotatorExampleSimulation() {
        initComponents();
        
        setPreferredSize(new Dimension(300, 300));
        
        rot = new Rotator(80, -90);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void timeElapsed(double deltaTime) {
        this.time += deltaTime;
        
        rot.calculateNewPosition(deltaTime);
    }

    @Override
    public void reset() {
        this.time = 0;
        
        rot.reset();
    }

    @Override
    public void draw(Graphics2D g2d) {
        g2d.fillOval(90, 90, 20, 20);
        
        g2d.drawLine(100, 100, (int)rot.getX() + 100, (int)rot.getY() + 100);
        g2d.setColor(Color.RED.darker());
        g2d.fillOval((int)rot.getX() + 90, (int)rot.getY() + 90, 20, 20);
    }

    @Override
    public String getSimulationName() {
        return "Rotator Example Simulation";
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
